version: '3'
services:
  web:
    build: .
    command: python3 -m http.server 8000
    ports:
      - 3000:8000
    volumes:
      - .:/app
  crawler:
    build: .
    command: bash -c "while true; do export MYTUTOR_EMAIL=${MYTUTOR_EMAIL} && export MYTUTOR_PASS=${MYTUTOR_PASS} && python3 app/src/scripts/scraping.py sleep 3h; done"
    volumes:
      - .:/app